#!/usr/bin/env bash

# determine script base and setup executable
SCRIPT_BASE="$(dirname "$(readlink -f "$0")")"
APPLICATION_EXEC="${SCRIPT_BASE}/bin/$(basename "$0")"

# call application
exec "${APPLICATION_EXEC}" "$@"