#!/usr/bin/env bash

# determine script base and setup executable
SCRIPT_BASE="$(dirname "$(readlink -f "$0")")"
APPLICATION_EXEC="${SCRIPT_BASE}/bin/$(basename "$0")"

# set NDDS home directory
export NDDSHOME
NDDSHOME="${SCRIPT_BASE}"

# call application
exec "${APPLICATION_EXEC}" "$@"
